### ISSUE TITLE
AMOEBA advanced potential energies workshop (2016)

### ISSUE THREAD

**Issue by D16ERG** [rtb1c13/amoebaworkshop#1]
Dear Sir,

In the past, the "AMOEBA advanced potential energies workshop" 
was of great practical and theoretical use for learning Tinker.
Since this workshop is no longer available online; I would like to ask 
if it is still possible to obtain the said or similar learning resources?

So far; I did find alternative TINKER resources. The AMOEBA advanced 
potential energies workshop was nevertheless unique in its explanation
of Tinker its practical use and the AMOEBA force field its theory. So far;
I did manage to find the following workshops and tutorials:

1. Chembytes: Build molecular structures for TINKER 
    http://chembytes.wikidot. com/tnk-tut00 
2. Chembytes: Build a solvent box in TINKER 
    http://chembytes.wikidot.com/solventbox 
3. AMOEBA advanced potential energies workshop 
    https://sites.google.com/ site/amoebaworkshop/exercise-1
4. Tinkergpu:Tinker-tut 
    https://biomol.bme.utexas.edu/tinkergpu/index.php?title= Tinkergpu:Tinker-tut
5. CECAM Winter School 2023: Tinker
    https://github.com/louislagardere/winter-school-2023/blob/main/Tinker_Winter_School.pdf

Besides this; I still had a cached version of the workshop its first
exercise. This page printout is visible in the attached PDF.
[Exercise 1 - Getting started with Tinker - AMOEBA advanced potential energies workshop.pdf](https://github.com/rtb1c13/amoebaworkshop/files/12456075/Exercise.1.-.Getting.started.with.Tinker.-.AMOEBA.advanced.potential.energies.workshop.pdf)

Kind regards

**Comment by D16ERG** [comment]
[AMOEBA Workshop Google Site.zip](https://github.com/rtb1c13/amoebaworkshop/files/14274593/AMOEBA.Workshop.Google.Site.zip)

Dear Sir,

In a stroke of luck; the aforementioned Google Site has been automatically backed up by the Wayback Machine. A functioning copy of the [AMOEBA advanced potential energies workshop](https://web.archive.org/web/20210125225203/https://sites.google.com/site/amoebaworkshop/) can therefore be found in the Internet Archive. To further prevent the workshop data from being lost; I have also created an offline copy of the workshop site and the accompanying slides. An archived version of these files can be found in the compressed attachment. Could these files be added to the Workshop its main GitHub page?

Kind regards

**Comment by rtb1c13** [comment]
Hi @D16ERG

Thank you for your work on this! Apologies for the delay, I've now added the files you found as commit `d3d4f81`, I hope this is useful to you and others in the future. I appreciate the effort you put in to find the old website after it had been lost 🙂 

Thanks again, and I'll now close this issue - please feel free to reopen it if there's anything further to add.
